# JupyTer Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Scalable Data Science & Distributed Machine Learning
author: ScaDaMaLe Team
logo: logo.png
copyright: "2020 Creative Commons Zero v1.0 Universal"  # Copyright year to be placed in the footer

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: 'off'

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: ScaDaMaLe.tex

# Information about where the book exists on the web
repository:
  url: https://lamastex.github.io/ScaDaMaLe/index.html # Online location of your book
  path_to_book: docs  # Optional path to your book, relative to the repository root
  branch: master  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true
#  baseurl: ScaDaMaLe/

#only_build_toc_files: true
