site_name: Datafiles
site_description: A file-based ORM for dataclasses.
site_author: Jace Browning

repo_url: https://github.com/jacebrowning/datafiles
edit_uri: https://github.com/jacebrowning/datafiles/edit/main/docs

theme:
  name: readthedocs

markdown_extensions:
  - codehilite:
      noclasses: true
  - toc:
      toc_depth: 2

nav:
  - Overview: index.md
  - API:
    - Model: api/model.md
    - Manager: api/manager.md
    - Mapper: api/mapper.md
  - Types:
    - Builtins: types/builtins.md
    - Containers: types/containers.md
    - Extended Types: types/extensions.md
    - Custom Types: types/custom.md
    - Generic Types: types/generics.md
  - Extras:
    - File Formats: formats.md
    - Utilities: utilities.md
    - Settings: settings.md
  - About:
    - Release Notes: about/changelog.md
    - Contributor Guide: about/contributing.md
    - License: about/license.md
