DESCRIBE HISTORY students

/*
| version | timestamp                    | userId      | userName            | operation    | operationParameters                                                          | job  | notebook                          | clusterId            | readVersion | isolationLevel    | isBlindAppend | operationMetrics                                                                                                                                                                                     | userMetadata | engineInfo                          |
|---------|------------------------------|-------------|---------------------|--------------|------------------------------------------------------------------------------|------|-----------------------------------|----------------------|-------------|-------------------|---------------|------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|--------------|-------------------------------------|
| 8       | 2023-03-12T23:56:22.000+0000 | 7.63278E+15 | efraser25@gmail.com | OPTIMIZE     | {"predicate":"[]","zOrderBy":"[\"id\"]","batchId":"0","auto":"false"}        | null | {"notebookId":"3466516260957501"} | 0306-232745-o5qeeo65 | 7           | SnapshotIsolation | FALSE         | {"numRemovedFiles":"4","numRemovedBytes":"4236","p25FileSize":"1098","minFileSize":"1098","numAddedFiles":"1","maxFileSize":"1098","p75FileSize":"1098","p50FileSize":"1098","numAddedBytes":"1098"} | null         | Databricks-Runtime/11.3.x-scala2.12 |
| .       | .                            | .           | .                   | .            | .                                                                            | .    | .                                 | .                    | .           | .                 | .             | .                                                                                                                                                                                                    | .            | .                                   |
| 1       | 2023-03-12T23:29:06.000+0000 | 7.63278E+15 | efraser25@gmail.com | WRITE        | {"mode":"Append","partitionBy":"[]"}                                         | null | {"notebookId":"3466516260957501"} | 0306-232745-o5qeeo65 | 0           | WriteSerializable | TRUE          | {"numFiles":"1","numOutputRows":"1","numOutputBytes":"1055"}                                                                                                                                         | null         | Databricks-Runtime/11.3.x-scala2.12 |
| 0       | 2023-03-12T23:28:55.000+0000 | 7.63278E+15 | efraser25@gmail.com | CREATE TABLE | {"isManaged":"true","description":null,"partitionBy":"[]","properties":"{}"} | null | {"notebookId":"3466516260957501"} | 0306-232745-o5qeeo65 | null        | WriteSerializable | TRUE          | {}                                                                                                                                                                                                   | null         | Databricks-Runtime/11.3.x-scala2.12 |
*/